// <auto-generated />
using System;
using Many_To_Many_With_CLR_Join_Type;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Many_To_Many_With_CLR_Join_Type.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210307133945_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Many_To_Many_With_CLR_Join_Type.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Many_To_Many_With_CLR_Join_Type.Membership", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int?>("GroupId1")
                        .HasColumnType("int");

                    b.Property<string>("MembershipDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonId1")
                        .HasColumnType("int");

                    b.HasKey("GroupId", "PersonId");

                    b.HasIndex("GroupId1");

                    b.HasIndex("PersonId");

                    b.HasIndex("PersonId1");

                    b.ToTable("Membership");
                });

            modelBuilder.Entity("Many_To_Many_With_CLR_Join_Type.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Many_To_Many_With_CLR_Join_Type.Membership", b =>
                {
                    b.HasOne("Many_To_Many_With_CLR_Join_Type.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Many_To_Many_With_CLR_Join_Type.Group", null)
                        .WithMany("GroupMemberships")
                        .HasForeignKey("GroupId1");

                    b.HasOne("Many_To_Many_With_CLR_Join_Type.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Many_To_Many_With_CLR_Join_Type.Person", null)
                        .WithMany("Memberships")
                        .HasForeignKey("PersonId1");

                    b.Navigation("Group");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Many_To_Many_With_CLR_Join_Type.Group", b =>
                {
                    b.Navigation("GroupMemberships");
                });

            modelBuilder.Entity("Many_To_Many_With_CLR_Join_Type.Person", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
